baseURL = "https://kwasnyy.pl"
title = "kkwasnyy.pl"

# Use the Nightfall theme (uncomment the next line)
theme = "nightfall"
# theme = "ananke"   # previous theme, now replaced

languageCode = "en-us"
buildDrafts = false
enableRobotsTXT = true

[params]
user = "kkwasny"
hostname = "kwasnyy.pl"
  description = "A blog about my personal journey and projects."
  customCSS = ["css/custom.css"]

  # Define the author as an object for Nightfall
  [params.author]
    name = "Kacper Kwaśny"
    bio  = "Kocham protokoły."


  # Define navigation as expected by Nightfall:
  nav = [
    { title = "Home", url = "/" },
    { title = "About", url = "/about/" },
    { title = "Posts", url = "/posts/" }
  ]


[[params.social]]
key = 0
name = "github"
url = "https://github.com/kacpekwasny"
# icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO

[[params.social]]
key = 1
name = "linkedin"
url = "https://www.linkedin.com/in/kacper-kwasny/"

[[params.social]]
key = 2
name = "email"
url = "mailto:kwasny.kg@gmail.com"

# Define your main menu (useful for navigation)
[menu]

  [[menu.header]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

  [[menu.header]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 2

  [[menu.header]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 3

# Define taxonomies for categorization
[taxonomies]
  tag      = "tags"
  category = "categories"

# Configure permalinks for your posts
[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"

