FROM klakegg/hugo:0.111.3-ext-alpine

WORKDIR /app

# Copy Hugo configuration files
COPY hugo.yaml ./
COPY themes/ ./themes/
COPY layouts/ ./layouts/
COPY static/ ./static/

# Expose Hugo's default port
EXPOSE 1313

# Run Hugo in server mode with live reload and bind to all interfaces
CMD ["server", "--bind", "0.0.0.0", "--port", "1313", "--disableFastRender", "--watch"]
